import DashboardWrapper from '@/components/layout'

export const metadata = {
  title: 'Homepage',
  description: 'Generated by create next app',
}

export default async function DashboardLayout({ children }) {
  return <DashboardWrapper>{children}</DashboardWrapper>
}
